server:
  port: 8090
  context-path: /

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: hawoo3499@gmail.com
    password: vynkvwuosadijsfm
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://localhost:3308/nong4
#    logback
#    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#    url: jdbc:log4jdbc:mysql://localhost:3308/nong4
    username: root
    password: 1234
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 30MB
      location: D:\springImg
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
mybatis:
  mapper-locations: mybatis-mapper/*.xml
  type-aliases-package: com.spring.nong4